name: Sync Repository to GitLab

on:
  push


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Pull changes from GitLab
      run: |
        git remote add gitlab ${{secrets.GITLAB_URL}}
        git fetch gitlab
        git merge gitlab/master --allow-unrelated-histories
    - name: Sync to GitLab
    
      uses: keninkujovic/gitlab-sync@2.1.0
      with:
        gitlab_url: ${{ secrets.GITLAB_URL }}
        username: ${{ secrets.USERNAME }}
        gitlab_pat: ${{ secrets.GITLAB_PAT }}
